apiVersion: v1
kind: Service
metadata:
  name: node-express-docker-service
spec:
  selector:
    app: node-express-docker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
